export const ProjectsList = [
  {
    id: 1,
    name: "Rock-Paper-Scissor",
    link: "https://habibzad.github.io/rpsGame/",
    github: "https://github.com/Habibzad/rpsGame",
    sammary: "You play this simple fun game against the computer.",
    tech: "HTML, CSS, Javascript",
  },
  {
    id: 2,
    name: "GPA Calculator",
    link: "https://habibzad.github.io/gpa-calculator/",
    github: "https://github.com/Habibzad/gpa-calculator",
    sammary: "It calculates the grade point average",
    tech: "HTML, CSS, Javascript",
  },
  {
    id: 3,
    name: "Digital Clock",
    link: "https://codepen.io/amhabibzad/full/KKMOrWQ",
    github: "https://github.com/Habibzad/digital-clock",
    sammary: " A simple digital clock",
    tech: "HTML, CSS, Javascript",
  },
  {
    id: 4,
    name: "Random quotes",
    link: "https://habibzad.github.io/inspirational-quotes/",
    github: "https://github.com/Habibzad/inspirational-quotes",
    sammary: "Random quotes",
    tech: "HTML, CSS, Javascript",
  },
  {
    id: 5,
    name: "To Do List",
    link: "https://habibzad.github.io/to-do-list/",
    github: "https://github.com/Habibzad/to-do-list",
    sammary: "To Do List",
    tech: "HTML, CSS, Javascript",
  },
  {
    id: 6,
    name: "Weather App",
    link: "https://codepen.io/amhabibzad/full/OJRNPoP",
    github: "https://github.com/Habibzad/WeatherApp",
    sammary: "Weather App",
    tech: "HTML, CSS, Javascript",
  },
];
